### ISSUE TITLE
cdncheck not correctly updated

### ISSUE THREAD

**Issue by edoardottt** [projectdiscovery/pdtm#375]
### pdtm version:

[INF] Current Version: v0.0.9

### Current Behavior:

When I execute `pdtm -ua`, the tool keeps installing the latest version of cdncheck, but in reality it doesn't install it.

### Expected Behavior:

[INF] cdncheck: already up to date

### Steps To Reproduce:

1. `pdtm -ia`
2. `pdtm -ua`

### Anything else:

pdtm -ia
```
 edoardottt@edoardottt > pdtm -ia
...
[INF] Current pdtm version v0.0.9 (latest)
[INF] aix: already installed
[INF] alterx: already installed
[INF] asnmap: already installed
[INF] cdncheck: already installed
[INF] chaos-client: already installed
...
```

pdtm -ua
```
 edoardottt@edoardottt > pdtm -ua
...
[INF] Current pdtm version v0.0.9 (latest)
[INF] aix: already up to date
[INF] alterx: already up to date
[INF] asnmap: already up to date
[INF] updating cdncheck...

                                                                              
  ## What's Changed                                                           
                                                                              
  ### Other Changes                                                           
                                                                              
  • update deps to bart instead of cidranger by @Ice3man543 in                
  https://github.com/projectdiscovery/cdncheck/pull/280                       
                                                                              
  Full Changelog:                                                             
  https://github.com/projectdiscovery/cdncheck/compare/v1.0.11...v1.1.0       


[INF] updated cdncheck to 1.1.0 (latest)
...
```

cdncheck info
```
 edoardottt@edoardottt > which cdncheck
/home/edoardottt/.pdtm/go/bin/cdncheck
 edoardottt@edoardottt > /home/edoardottt/.pdtm/go/bin/cdncheck
...
[INF] Current cdncheck version v1.0.11 (outdated)
[INF] No results found.
```

**Comment by ehsandeep** [comment]
@edoardottt should be fixed now!

**Comment by edoardottt** [comment]
Now pdtm updates cdncheck to V1.1.1, but keeps updating as before. For what I see it's not fixed

**Comment by Sh4d0wHunt3rX** [comment]
https://github.com/projectdiscovery/cdncheck/issues/103#issuecomment-2665731937

**Comment by dogancanbakir** [comment]
Could you retry?
